### ISSUE TITLE
[Error 3201] Import Whitelist from Trusted Host. IOException. [MS_HOST_COMMUNICATION_ERROR]

### ISSUE THREAD

**Issue by BurtonFeng** [opencit/opencit#104]
I seem to be getting an IOException error when trying to Import the Whitelist from Trusted Host.
![image](https://user-images.githubusercontent.com/22104106/43523246-cb42784a-9569-11e8-85b4-50e89b640712.png)

Below are the logs from catalina.out and trustagent.log:
**catalina.out**
![image](https://user-images.githubusercontent.com/22104106/43523442-60def0a4-956a-11e8-8655-577734c944d0.png)

**trustagent.log**
![image](https://user-images.githubusercontent.com/22104106/43523517-9f144a68-956a-11e8-98ce-b5a72a131746.png)

Running on:
OpenCIT 3.2.1 on Ubuntu 16.04
TrustAgent on Ubuntu 16.04 running tboot-1.9.6

**Comment by hdxia** [comment]
Can you please turn on debug mode on both the attestation server and trust agent to get more debug information? it seems the attestation server and trust agent are communicating. however, something wrong happened so the attestation cannot get what it needs. also, the time stamp on the attestation server and trust agent seems not synced. this should be addressed first otherwise, it cause problem.

**Comment by ddhawal** [comment]
#1 Errors from catalina.out
1. Check if all parameters are right
2. Check if trustagent is running
3. Check if dates are in sync on trustagent and attestation server

#2 Errors in trustagent.log
Create and deploy manifest.xml i.e list of files/folders and symlinks on trustagent using Trust Director and restart Host.

**Comment by ddhawal** [comment]
Additionally, 
Check whether the TA is running on 0.0.0.0:1443 or <IP Address>:1443.
Use IP Address , if it runs on 0.0.0.0:1443, HVS is not able to communicate and we see the same generic error.

**Comment by BurtonFeng** [comment]
Thanks for getting back to me so quickly!
   - All the parameters should be right 
       - The trustagent is running on a valid 3 dot ip, so I am using 3.1.X.X:1443
   - The trustagent is running
   - The time on the trust agent was changed to match the attestation server

It seems to me that the TCB measurement file is not being generated by the measure_host script.
Here is the debug logs from catalina.out and trustagent.log.

Thanks!
[trustagent.log](https://github.com/opencit/opencit/files/2253969/trustagent.log)

[catalina.txt](https://github.com/opencit/opencit/files/2253971/catalina.txt)

**Comment by ddhawal** [comment]
Did you complete #2 Trust Director step mentioned above? Those steps generate TCB measurement file.

trustagent.log
It has Tpm ownership errors. Did you resolve those? Tpm needs to be cleared before installing trustagent.

**Comment by BurtonFeng** [comment]
I have used the Trust Director, however I do not see the manifest.xml files or the /boot/trust directory. I am able to download the tar, which includes the manifest and policy files. 
The same IOException error is still present.

![image](https://user-images.githubusercontent.com/22104106/43597874-50907492-9651-11e8-8e94-b82093d3d770.png)

As for the tpm ownership error, the errors seen were from earlier when I was setting the trust agent up again. The tpm has since been cleared and tagent setup was run successfully.

**Comment by BurtonFeng** [comment]
I traced the errors in measure_host and manually extracted the policy & manifest xml files from the trust director to the specified location (from the script). 
After fixing this and running the script again, I was able to trace to what caused the IOException, which was resolved by: https://github.com/opencit/opencit/issues/61
