### ISSUE TITLE
what's the difference between opencit and openattestation

### ISSUE THREAD

**Issue by kaizi-8lab** [opencit/opencit#109]
I used open attestation in my previous work， i find opencit similar to open attetation,  what's the difference between opencit and openattestation?

**Comment by ddhawal** [comment]
Opencit has much more use cases than open attestation, it has VM and docker integrity, confidentiality. Along with open attestation, opencit is also stale now. Please refer to https://01.org/intel-secl which makes host attestation simpler and easy management along with other use-cases supported.
