### ISSUE TITLE
TPM 2.0 with Trust agent

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#16]
In the trsust agent installation guide says that TPM 1.2 is needed for the installation. Is it also possible to succesfully install the Trust Agent  with TPM 2.0 ??

**Comment by ZahediAquino** [comment]
No, support for TPM 2.0 is in our planned for the first half of 2017.

**Comment by ZahediAquino** [comment]
Nothing to solve, I am closing. Please reopen if something else comes up.

**Comment by jemm14** [comment]
yeah, I can not find any Computer mit TXT/TPM1.2 on the market, all are TPM 2.0 , any suggestion?
