### ISSUE TITLE
Build failure due to VMware dependencies

### ISSUE THREAD

**Issue by psmiraglia** [opencit/opencit#18]
The building of `opencit/opencit`  (at branch `release-cit-2.1`) fails due to some missing dependencies about VMware. No problems instead for `opencit/opencit-external-artifacts` and `opencit/opencit-util`.

After some attempts, I identified the problem in `vijava` installed by `opencit-external-artifacts`. In particular, some classes (under `com.vmware.vim25`) required by the VMware modules (e.g. `mtwilson-vmware-hostagent`) result to be not available in the classpath.

I tried to disable all the `*-vmware-*` modules in the pom files but nothing changed. The build fails at `mtwilson-portal` due to the same problem.

**Comment by ZahediAquino** [comment]
@psmiraglia can you paste the console output? Also what java version is being used by your system (java -version)?

**Comment by psmiraglia** [comment]
@ZahediAquino thank you for your rapid answer.

About VMware issues, it was my fault. During `opencit-extarnal-artifact` building I copied `vijava55b20130927.zip` instead of unzipping it and copying `vijava55b20130927.jar`. The building is gone ahead, but now I have some problems with `mtwilson-tpm-commands`. See issue #21.

**Comment by psmiraglia** [comment]
@ZahediAquino should I open a new issue? The topic is changed now.

**Comment by adolfovega** [comment]
Yes please, could you open a new issue? This seems to be related to tpm-tools right?

Thanks!

Adolfo,

**Comment by psmiraglia** [comment]
Done! See issue #21.
