### ISSUE TITLE
Several question and error with 2.2 Beta

### ISSUE THREAD

**Issue by 19LukaModric** [opencit/opencit#20]
Hi,
I am working on the installation of trust agent with 2.2 Beta. But I met some question and error as followed. Hope to get some advice and help from you.
- I completed the Server installation on Ubuntu 14.04, and installing the Trust Agent on Centos 7.2. Is this OK for Open CIT working well with the different platform?
- For installing the Trust Agent on CentOS 7.2, is it necessary to cancel the note of the mtwilson-trustagent-rhel component as followed?

/root/opencit/installers/pom.xml
line23: <module>mtwilson-trustagent-rhel</module>
- When I canceled the note, I executed 'ant' of opencit and I met an error of the mtwilson-trustagent-rhel. The log is as followed:
  
   [exec] [INFO] ------------------------------------------------------------------------
   [exec] [INFO] Building Trust Agent Linux Installer RHEL 2.2-SNAPSHOT
   [exec] [INFO] ------------------------------------------------------------------------
   [exec] [WARNING] The POM for com.intel.mtwilson.tbootxm.packages:tbootxm:bin:rhel:2.2-SNAPSHOT is missing, no dependency information available
   [exec] [INFO] ------------------------------------------------------------------------
   [exec] [INFO] Reactor Summary:
   [exec] [INFO] 
   [exec] [INFO] mtwilson-common .................................... SUCCESS [  3.745 s]
   [exec] [INFO] Common Crypto ...................................... SUCCESS [  6.737 s]
   ......
  
   [exec] [INFO] mtwilson-tpm-commands .............................. SUCCESS [02:54 min]
   [exec] [INFO] mtwilson-trustagent ................................ SUCCESS [  4.711 s]
   [exec] [INFO] mtwilson-tpm2-packages ............................. SUCCESS [  0.842 s]
   [exec] [INFO] Trust Agent Linux Installer RHEL ................... FAILURE [  0.042 s]
   [exec] [INFO] Trust Agent Linux Installer ........................ SKIPPED
   [exec] [INFO] mtwilson-manifest-xml .............................. SKIPPED
   [exec] [INFO] mtwilson-file-client-jaxrs2 ........................ SKIPPED
   [exec] [INFO] mtwilson-test ...................................... SKIPPED
   [exec] [INFO] mtwilson-html5 ..................................... SKIPPED
   [exec] [INFO] mtwilson-configuration-settings-ws-v2 .............. SKIPPED
   [exec] [INFO] mtwilson-extensions-ws-v2 .......................... SKIPPED
   [exec] [INFO] mtwilson-vm-attestation-client-jaxrs2 .............. SKIPPED
   [exec] [INFO] mtwilson-packages .................................. SKIPPED
   [exec] [INFO] mtwilson-maven-build ............................... SKIPPED
   [exec] [INFO] ------------------------------------------------------------------------
   [exec] [INFO] BUILD FAILURE
   [exec] [INFO] ------------------------------------------------------------------------
   [exec] [INFO] Total time: 06:16 min
   [exec] [INFO] Finished at: 2016-10-08T15:41:50+08:00
   [exec] [INFO] Final Memory: 353M/975M
   [exec] [INFO] ------------------------------------------------------------------------
   [exec] [ERROR] Failed to execute goal on project mtwilson-trustagent-rhel: Could not resolve dependencies for project com.intel.mtwilson.linux:mtwilson-trustagent-rhel:pom:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson.tbootxm.packages:tbootxm:bin:rhel:2.2-SNAPSHOT -> [Help 1]
   [exec] [ERROR] 
   [exec] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
   [exec] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
   [exec] [ERROR] 
   [exec] [ERROR] For more information about the errors and possible solutions, please read the following articles:
   [exec] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
   [exec] [ERROR] 
   [exec] [ERROR] After correcting the problems, you can resume the build with the command
   [exec] [ERROR]   mvn <goals> -rf :mtwilson-trustagent-rhel
   [exec] Result: 1

BUILD FAILED
/root/opencit/build.xml:79: Failed to build maven project

**Comment by adolfovega** [comment]
According to the pdf documentation available for 2.2 beta release the supported OS for the compute nodes using TrustAgent are basically these: Windows, Ubuntu or RedHat. No CentOS support is provided yet.

Thanks!
