### ISSUE TITLE
2.2.Beta Installation issue

### ISSUE THREAD

**Issue by choudhary01** [opencit/opencit#23]
After successful building of 2.2.Beta , I am running into Attestation Service installation issues. I followed steps in product guide and created mtwilson.env file in /root using default values.
Installation started with complain of missing MTWILSON_HOME and MTWILSON_USER variables which I created. It seems mtwilson-attestation-service-installer-2.2-SNAPSHOT.bin exits within seconds without any meaningful error.
Can you please help?.

root@ubuntu:~# ./mtwilson-attestation-service-installer-2.2-SNAPSHOT.bin 
Verifying archive integrity... All good.
Uncompressing mtwilson-attestation-service-installer-2.2-SNAPSHOT  100%  
Missing environment variable: MTWILSON_HOME
root@ubuntu:~# export MTWILSON_HOME=/root
root@ubuntu:~# ./mtwilson-attestation-service-installer-2.2-SNAPSHOT.bin 
Verifying archive integrity... All good.
Uncompressing mtwilson-attestation-service-installer-2.2-SNAPSHOT  100%  
Missing environment variable: MTWILSON_USERNAME
root@ubuntu:~# export MTWILSON_USERNAME=root
root@ubuntu:~# ./mtwilson-attestation-service-installer-2.2-SNAPSHOT.bin 
Verifying archive integrity... All good.
Uncompressing mtwilson-attestation-service-installer-2.2-SNAPSHOT  100%  
Missing file: /opt/mtwilson/share/scripts/functions
Installing aikqverify prereqs...

root@ubuntu:~/opencit/installers# cd mtwilson-server
root@ubuntu:~/opencit/installers/mtwilson-server# ls
makebin-auto.sh  pom.xml  src  target
root@ubuntu:~/opencit/installers/mtwilson-server# cd target/
root@ubuntu:~/opencit/installers/mtwilson-server/target# ls
mtwilson-server-2.2-SNAPSHOT      mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit
mtwilson-server-2.2-SNAPSHOT.bin  mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit.bin
root@ubuntu:~/opencit/installers/mtwilson-server/target# ./mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit.bin
Verifying archive integrity... All good.
Uncompressing mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit  100%  
Loading environment variables from /root/mtwilson.env
Reading properties from file [/etc/intel/cloudsecurity/attestation-service.properties].....Done
Installing Java...
Java already installed at /usr/lib/jvm/jdk1.7.0_51
Replacing java.security file, existing file will be backed up
/usr/lib/jvm/jdk1.7.0_51/jre/lib/security/java.security.2016-10-09.0643
Reading package lists... Done
Building dependency tree  
Reading state information... Done
zip is already the newest version.
openssl is already the newest version.
unzip is already the newest version.
unzip set to manually installed.
The following NEW packages will be installed:
  authbind xmlstarlet
0 upgraded, 2 newly installed, 0 to remove and 369 not upgraded.
Need to get 310 kB of archives.
After this operation, 634 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/universe xmlstarlet amd64 1.5.0-1 [290 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty/main authbind amd64 2.1.1 [19.6 kB]
Fetched 310 kB in 1s (204 kB/s)
Selecting previously unselected package xmlstarlet.
(Reading database ... 172246 files and directories currently installed.)
Preparing to unpack .../xmlstarlet_1.5.0-1_amd64.deb ...
Unpacking xmlstarlet (1.5.0-1) ...
Selecting previously unselected package authbind.
Preparing to unpack .../authbind_2.1.1_amd64.deb ...
Unpacking authbind (2.1.1) ...
Processing triggers for doc-base (0.10.5) ...
Processing 1 added doc-base file...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up xmlstarlet (1.5.0-1) ...
Setting up authbind (2.1.1) ...
Extracting application...
Available TLS policies: certificate, certificate-digest, public-key, public-key-digest, TRUST_FIRST_CERTIFICATE, INSECURE
Mt Wilson Allowed TLS Policies:  [certificate,certificate-digest,public-key,public-key-digest,TRUST_FIRST_CERTIFICATE] certificate,certificate-digest,public-key,public-key-digest,TRUST_FIRST_CERTIFICATE
Configuration path validation failed. Verify path meets acceptable directory constraints: /root/configuration/mtwilson.properties
root@ubuntu:~/opencit/installers/mtwilson-server/target# ls
mtwilson-server-2.2-SNAPSHOT      mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit
mtwilson-server-2.2-SNAPSHOT.bin  mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit.bin

root@ubuntu:~/opencit/installers/mtwilson-server/target# ./mtwilson-server-2.2-SNAPSHOT.bin 
Verifying archive integrity... All good.
Uncompressing mtwilson-server-2.2-SNAPSHOT  100%  
Loading environment variables from /root/mtwilson.env
export PATH=/root/bin:$PATH Already there in user profile
export MTWILSON_HOME=/root Already there in user profile
Reading properties from file [/etc/intel/cloudsecurity/mtwilson.properties].....Done
Reading properties from file [/etc/intel/cloudsecurity/attestation-service.properties].....Done
Installing Java...
Cannot install Java: missing package name
Replacing java.security file, existing file will be backed up
/usr/lib/jvm/jdk1.7.0_51/jre/lib/security/java.security.2016-10-09.0644
Reading package lists... Done
Building dependency tree  
Reading state information... Done
authbind is already the newest version.
zip is already the newest version.
xmlstarlet is already the newest version.
openssl is already the newest version.
unzip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 369 not upgraded.
Extracting application...
Default TLS policy is insecure; the product guide contains information on enabling secure TLS policies
Available TLS policies: certificate, certificate-digest, public-key, public-key-digest, TRUST_FIRST_CERTIFICATE, INSECURE
Mt Wilson Allowed TLS Policies:  [certificate,certificate-digest,public-key,public-key-digest,TRUST_FIRST_CERTIFICATE] certificate,certificate-digest,public-key,public-key-digest,TRUST_FIRST_CERTIFICATE
Configuration path validation failed. Verify path meets acceptable directory constraints: /root/configuration/mtwilson.properties

**Comment by choudhary01** [comment]
I am able to install the CIT server.

Following addition in 2.2 product guide would be helpful which I found it https://github.com/opencit/opencit/wiki/Open-CIT-2.0.7---Server-Product-Guide#20-installation

Copy the Cloud Integrity Technology Attestation Server installation bin file opencit/installers/mtwilson-server/target/mtwilson-server-2.0.7-jdk_glassfish_monit.bin to the /root directory of an Ubuntu virtual machine.
Run the following command to execute the installation script:
$ ./mtwilson-server-2.0.7-jdk_glassfish_monit.bin

**Comment by adolfovega** [comment]
Hi,
I am glad to know everything is ok now.
Thank you for your feedback, we appreciate it! 

Thanks!

Adolfo,
