### ISSUE TITLE
Unable to retrieve the TPM values from the host. Verify the host TXT configuration. [MS_INVALID_ATTESTATION_REPORT] [3209]

### ISSUE THREAD

**Issue by aforalee** [opencit/opencit#26]
i am using dell proliant dl380 g7 as my trust agent host. 
Steps I followed.
I installed Attestation service in linux 14.04 
then i installed trust agent on linux 14.04
i boot server on trusted boot.
i ran all everything according to documentation. 
After my trust agent is installed and running. 
I went to attestation server mtwilson-portal
then whitelist and tried to  import Whitelist from Trusted Host. 

I think my server is not supporting TXT but i am confused because i read this that my server is already tested with intel cit 
(https://github.com/opencit/opencit/wiki/Open-CIT-2.2-Product-Guide#52-tested-platforms)

**Comment by ryansavino** [comment]
Please enable DEBUG logging (logging configuration file: /opt/trustagent/configuration/logback.xml) and provide logfile:
1. remove or comment any logger starting with "com.intel"
    i.e.: \<logger name="com.intel.dcsg.cpg" level="INFO"/>
2. change root level logger to DEBUG
    i.e.: \<root level="${TRUSTAGENT_LOG_LEVEL:-DEBUG}">
3. tagent restart
4. tagent setup
5. attach logfile for analysis: /opt/trustagent/logs/trustagent.log

Also, please provide the output of running 'txt-stat'.

**Comment by aforalee** [comment]
thanks for help. i changed server because that was not supporting txt
