### ISSUE TITLE
How can i find the project "mtwilson-maven-java"?

### ISSUE THREAD

**Issue by zhq0918** [opencit/opencit#28]
Such as the title,I can't build the project,because the project "mtwilson-maven-java" is missing.
![image](https://cloud.githubusercontent.com/assets/24485518/21080731/8cb096f6-bff1-11e6-85a4-5fc203a88b24.png)

**Comment by ryansavino** [comment]
You must build the dependent repositories first. That specific project is in the opencit-util repo.

**Comment by zhq0918** [comment]
Thank you,ryansavino.Let me try it.
