### ISSUE TITLE
Why the project “mtwilson-maven-build-coreutil-root” can‘t build？Help me。

### ISSUE THREAD

**Issue by zhq0918** [opencit/opencit#29]
# **The project  “mtwilson-maven-build-coreutil-root” can‘t build，And the log as fllows：**
cd D:\opencit-util-release-cit-2.2; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_112" M2_HOME=D:\\apache-maven-3.3.9 cmd /c "\"\"D:\\apache-maven-3.3.9\\bin\\mvn.cmd\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 clean install\""
Scanning for projects...
[11111.txt](https://github.com/opencit/opencit/files/648175/11111.txt)

[ERROR] Some problems were encountered while processing the POMs:
## Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13
 @ 
## The build could not read 8 projects -> [Help 1]
  
  The project com.intel.mtwilson.services:mtwilson-configuration-settings-ws-v2:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-configuration-settings-ws-v2\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-data-bundle:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-data-bundle\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-help:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-help\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-html5:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-html5\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-html5-login-anon:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-html5-login-anon\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-html5-login-token:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-html5-login-token\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-junit:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-junit\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]
  
  The project com.intel.mtwilson.core:mtwilson-core-version:[unknown-version] (D:\opencit-util-release-cit-2.2\features\mtwilson-core-version\pom.xml) has 1 error
    Non-resolvable parent POM for com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT: Could not find artifact com.intel.mtwilson:mtwilson-maven-build-coreutil-root:pom:2.2-SNAPSHOT @ com.intel.mtwilson:mtwilson-maven-build-coreutil-maven:2.2-SNAPSHOT, D:\localrepo\com\intel\mtwilson\mtwilson-maven-build-coreutil-maven\2.2-SNAPSHOT\mtwilson-maven-build-coreutil-maven-2.2-SNAPSHOT.pom, line 10, column 13 -> [Help 2]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

## note： The project “mtwilson-maven-build-coreutil-maven” build success。

**Comment by ryansavino** [comment]
Are you building using the command "ant"?

**Comment by zhq0918** [comment]
@ryansavino ，my enviornment:The OS is  Win,and build the project in neatbeans.
![image](https://cloud.githubusercontent.com/assets/24485518/21137835/5b17dd04-c166-11e6-8fab-27784cf51400.png)
And I use ant build it,the log in the attach file.
[1213.txt](https://github.com/opencit/opencit/files/648838/1213.txt)

**Comment by ryansavino** [comment]
See the appropriate build order here:
https://github.com/opencit/opencit/wiki/Open-CIT-2.2-Product-Guide#322-building-the-source-code

Some projects can only be built from the linux side. You can compile individual java projects using netbeans, but their parents must be prebuilt and installed in your local maven repo or remote first.

**Comment by zhq0918** [comment]
Thank you very much。
