### ISSUE TITLE
showing untrusted host after just importing whitelist, help me

### ISSUE THREAD

**Issue by jlxcsy** [opencit/opencit#30]
My tagent works on NUC5i5myhe with ubuntu 16.04.
And attestation server works on my laptop with ubuntu 14.04.
steps I followed:
1) After login to admin account, import whitelist while registering host
![whitelist](https://cloud.githubusercontent.com/assets/7589089/21390777/81d7f42a-c7c3-11e6-8038-bc57013edd32.jpg)
2) But ,it shows untrusted after step 1）
![dashboard](https://cloud.githubusercontent.com/assets/7589089/21390790/915a4a38-c7c3-11e6-8ed5-a72c3274944f.jpg)
and it appears pcr17 value untrusted, but the hash values are identical with whitelist
![trust report](https://cloud.githubusercontent.com/assets/7589089/21390800/9e6fdb34-c7c3-11e6-908e-28d42d28579e.jpg)

here are logs:
1) the trustagent debug log :
[trustagent_debuglog.txt](https://github.com/opencit/opencit/files/666413/trustagent_debuglog.txt)
[trustagent_debuglog.pdf](https://github.com/opencit/opencit/files/668027/trustagent_debuglog.pdf)

2) attestation server log catalina.out :
[catalina_out.txt](https://github.com/opencit/opencit/files/668005/catalina_out.txt)

I couldnot figure it out, I would really appreciate any help.
Greetigs.

**Comment by ZahediAquino** [comment]
Do you also have the corresponding catalina.out log from the server?

**Comment by jlxcsy** [comment]
here are catalina logs:
[catalina_out.txt](https://github.com/opencit/opencit/files/666471/catalina_out.txt)
[catalina_20161221_log.txt](https://github.com/opencit/opencit/files/666474/catalina_20161221_log.txt)
Thanks.

**Comment by ZahediAquino** [comment]
Can you also enable DEBUG mode on the server side and post the catalina.out log again? Thanks

**Comment by ZahediAquino** [comment]
Can you also try to re-add the host but this time also enable the "Overwrite Whitelist" checkbox?

**Comment by jlxcsy** [comment]
First, sorry, please tell me how to enable DEBUG mode on the server ?
Then, after re-add operation with "Overwrite Whitelist", it still shows untrusted host as before.

**Comment by ZahediAquino** [comment]
Edit the following file on the server side:
/opt/mtwilson/configuration/logback.xml 

- Remove or comment any logger starting with com.intel i.e.: `<logger name="com.intel.dcsg.cpg" level="INFO"/>`
- Change root level logger to DEBUG i.e.: `<root level="${TRUSTAGENT_LOG_LEVEL:-DEBUG}">`
- Save the changes to the file
- run: `mtwilson restart`

**Comment by gwei3** [comment]
This is not an issue in CIT. Instead, it is a NUC issue: the measurement values got from event log for PCR17 can't reproduce the final PCR17 value via extending calculation. Please change to use other device.
