### ISSUE TITLE
Help with Issue #30

### ISSUE THREAD

**Issue by jlxcsy** [opencit/opencit#31]
Please I really need your help to correctly showing host trust status.
I have tried verything and nothing seems to work.
Any help with the Issue #30  is totally appreciated.

**Comment by aforalee** [comment]
are you booting on trusted mode?
when i use to boot on any other option i use to find this error but booting machine on trusted mode solves this problem. i suggest please try to boot it on trusted mode,
Thanks

**Comment by gwei3** [comment]
Please close this issue and just use #30 to track the issue.
