### ISSUE TITLE
How can i reslove the problem:java.security.cert.CertificateException: Server certificate is not trusted?

### ISSUE THREAD

**Issue by zhq0918** [opencit/opencit#33]
When I reInstall the opencit2.2 Project ,login the portal,there was a error :"java.security.cert.CertificateException: Server certificate is not trusted" in the page which name was Trust Dashboard,and the page import whitelist,the page which name is  "Import from Trusted Host " :the TLS Policy is none.

**Comment by ZahediAquino** [comment]
Does this happen everytime you load the page or is it intermittent? If possible, please post a screenshot of the screens.

To reinstall, did you uninstall the previous installation like this first to make sure everything is cleaned up correctly?
mtwilson erase-data
mtwilson erase-users --all
mtwilson uninstall

**Comment by zhq0918** [comment]
Thank you ZahediAquino,I have resolved the problem in your way。
