### ISSUE TITLE
Does the OpenStack TrustFilter work with Open CIT

### ISSUE THREAD

**Issue by ge0rgi** [opencit/opencit#37]
The comments in the implementation of  [trusted_filter](https://github.com/openstack/nova/blob/master/nova/scheduler/filters/trusted_filter.py) say it works with OpenAttestation. Since Open CIT superseded OAT does the trusted filter work with it as well? Are there any differences in filter configuration?

**Comment by ryansavino** [comment]
The trusted_filter that comes with OpenStack is overriden by the new asset_tag_filter that gets installed with OpenCIT. The old trusted_filter gets disabled automatically during the setup.

This item should be filed under opencit/opencit-openstack-extensions.
