### ISSUE TITLE
if I drop the admin user ,what can i do next step?

### ISSUE THREAD

**Issue by zhq0918** [opencit/opencit#41]
Today,I drop the admin user in the portal,and now I can not access the rest api "/v2/util/trustagent-env-file.html",next step ,if i want access the rest api"/v2/util/trustagent-env-file.html",what can i do?thanks.

**Comment by ryansavino** [comment]
what's the error? are you getting a 401?

what do you mean by "drop" user?

**Comment by zhq0918** [comment]
Sorry , the "drop" is impropriety,my mean is that:In mtwilson-portal,at the menu which named "list users", I deleted the user admin.and now  i can't access the rest api"/v2/util/trustagent-env-file.html" by my added administator.what can i do? thanks.

**Comment by ryansavino** [comment]
Looks like you got yourself in a sticky situation by deleting the admin user.

If you don't have a bunch of data that you need to save, I would suggest reinstalling.

If you are trying to retain data, I would suggest checking out the setup.sh script in installers/mtwilson-server to see how MC_FIRST_USERNAME gets created and approved. You can probably replicate these steps on the command line.

**Comment by zhq0918** [comment]
i can't find the MC_FIRST_USERNAME gets created in the setup.sh,it is so long.

**Comment by zhq0918** [comment]
i can't find the MC_FIRST_USERNAME gets created in the setup.sh,it is so long.
