### ISSUE TITLE
How can i add a new user to access the restful API?

### ISSUE THREAD

**Issue by zhq0918** [opencit/opencit#42]
I added a new user admin1 and then i granted the administartors role to the admin1 user.I want access the restful api with the admin1 user,but the admin1 user could not  accessed the restful api ,such as "/v2/privacyca/tpm-endorsement","https://192.168.0.1:8443/mtwilson/v2/hosts?nameEqualTo=192.168.0.2" etc,but how can i add a new user to access the restful API?and only the default  admin user can access the restful api?

**Comment by gwei3** [comment]
@ZahediAquino @ryansavino how can we let the new user added through portal be able to access the restful API urls instead of only access the portal?

**Comment by ryansavino** [comment]
Did you follow the steps here?
https://github.com/opencit/opencit/wiki/Open-CIT-2.2-Product-Guide#43113-new-user-creation

**Comment by dandantx** [comment]
yes, I followed the step you mentioned, and marked all roles for the new user, but still not able to access the restful api url - can't pass the login step.

**Comment by gwei3** [comment]
yes, I followed the step you mentioned, and marked all roles for the new user, but still not able to access the restful api url - can't pass the login step.

**Comment by zhq0918** [comment]
I checked the database, select a.id,a.user_id,b.role_id,c.username from mw_user_login_password a,mw_user_login_password_role b,mw_user c  where a.id = b.login_password_id and c.id = a.user_id,i found that only the initial user.
                  id                  |               user_id                |               role_id                | username
--------------------------------------+--------------------------------------+--------------------------------------+----------
 fa68f935-53eb-42fb-a28b-00501c378aaf | 0fc5678a-11c1-4c8a-a801-916896f4a163 | de714fb7-7a19-4c23-b9a7-e53f3c69d385 | admin
 fa68f935-53eb-42fb-a28b-00501c378aaf | 0fc5678a-11c1-4c8a-a801-916896f4a163 | 007a7e69-8519-4170-9d90-7b89eb68680a | admin
 46503451-ae3a-4d6c-aca6-9253f06fa4c7 | a345f9aa-9271-4d13-b5e5-526ad404ca18 | 8ea9e2e0-cf88-45f7-8459-5a5b0a81e4e6 | tagadmin
why it has'n the user that i  added which name is admin1?

**Comment by ryansavino** [comment]
@gwei3 did you approve the user from an admin account?

@zhq0918 yes, I checked this out. Looks like it's only creating a user_login_certificate and not the user_login_password record. The certificate user is only for use with our API client. We should probably add the user_login_password creation for this user when created through the portal. This can be tracked in a separate ticket.

To get you going, try this (from javadoc) as ADMIN user (basic authentication okay):
1. Get ID from:
GET https://[server]:8443/mtwilson/v2/users?nameEqualTo=[username]
2. On unix system, generate base64 encoded salt:
openssl rand -base64 8
3. On unix system, generate password hash (base64 encoded SHA256 hash) from generated salt and password:
echo -n $(echo -n [from_step_2] | base64 -d)[password] | openssl dgst -binary -sha256 | openssl base64
4. Create user_login_password for user:
POST https://[server]:8443/mtwilson/v2/users/[from_step_1]/login-passwords
JSON INPUT: {"password_hash":"[from_step_3]", "salt":"[from_step_2]", "iterations":1, "algorithm":"SHA256", "comment":"User access request"}
5. From output of step 4, grab user login password ID and enable it with roles:
PUT https://[server]:8443/mtwilson/v2/users/[from_step_1]/login-passwords/[from_step_4]
JSON INPUT: {"status":"APPROVED","enabled":true,"roles":["administrator"]}

**Comment by ryansavino** [comment]
There's also a command line option from the attestation service vm:
`export USER_PASSWORD=[password_content]`
`mtwilson login-password [username] env:USER_PASSWORD *:*`

Any permission can be substituted for the admin `*:*` separated by spaces.
i.e. tpm_endorsements:create tpm_endorsements:search etc.

**Comment by zhq0918** [comment]
Hi, @ryansavino @gwei3  , I tried it like what you said ,but i failed in the 4 step.The full progress as follows:
1、get id .https://192.168.0.1:8443/mtwilson/v2/users?nameEqualTo=admin1
<user_collection>
<users>
<user>
<id>787f5ef4-410d-4185-b195-774a4f521da3</id>
<username>admin1</username>
</user>
</users>
</user_collection>
2、generate base64 encoded salt。result:6GkirIIELCE=
3、 generate password hash (base64 encoded SHA256 hash) from generated salt and password:
echo -n $(echo -n 6GkirIIELCE= | base64 -d)password | openssl dgst -binary -sha256 | openssl base64
result:0tH5v/Hxz32jo0iKWznjC0pVtaNuQlrOeYfIPqB4Ndk=
4、post https://192.168.0.1:8443/mtwilson/v2/users/787f5ef4-410d-4185-b195-774a4f521da3/login-passwords.
jspon input:{"password_hash":"0tH5v/Hxz32jo0iKWznjC0pVtaNuQlrOeYfIPqB4Ndk=",
"salt":"6GkirIIELCE=",
"iterations":1,
"algorithm":"SHA256",
"comment":"User access request"}
result: **HTTP/1.1 415 Unsupported Media Type, javax.ws.rs.NotSupportedException**
that's my full progress. and in the 4 step, i used a toolkit which name is **restclient.**
what have i done wrong? Thank you @ryansavino and @gwei3 .

**Comment by zhq0918** [comment]
1、 https://192.168.0.1:8443/mtwilson/v2/users?nameEqualTo=admin1
getid:<id>**787f5ef4-410d-4185-b195-774a4f521da3**</id>
2、 generate base64 encoded salt:openssl rand -base64 8
**6GkirIIELCE=**
3、generate password hash (base64 encoded SHA256 hash) from generated salt and password:
echo -n $(echo -n 6GkirIIELCE= | base64 -d)password | openssl dgst -binary -sha256 | openssl base64
**0tH5v/Hxz32jo0iKWznjC0pVtaNuQlrOeYfIPqB4Ndk=**
4、Create user_login_password for user:
https://192.168.0.1:8443/mtwilson/v2/users/787f5ef4-410d-4185-b195-774a4f521da3/login-passwords
JSON INPUT: {"password_hash":"0tH5v/Hxz32jo0iKWznjC0pVtaNuQlrOeYfIPqB4Ndk=", "salt":"6GkirIIELCE=", "iterations":1, "algorithm":"SHA256", "comment":"User access request"}
result:
<user_login_password>
<id>**7ac309f0-69cc-4f20-8cc0-0904a92b6a5e**</id>
**<userId>787f5ef4-410d-4185-b195-774a4f521da3</userId>**
**<passwordHash>0tH5v/Hxz32jo0iKWznjC0pVtaNuQlrOeYfIPqB4Ndk=</passwordHash>**
**<salt>6GkirIIELCE=</salt>**
<iterations>1</iterations>
<algorithm>SHA256</algorithm>
<enabled>false</enabled>
<comment>User access request</comment>
</user_login_password>
5、From output of step 4, grab user login password ID and enable it with roles:
put https://192.168.0.1:8443/mtwilson/v2/users/787f5ef4-410d-4185-b195-774a4f521da3/login-passwords/7ac309f0-69cc-4f20-8cc0-0904a92b6a5e
 JSON INPUT: {"status":"APPROVED","enabled":true,"roles":["administrator"]}
result :**<user_login_password><id>7ac309f0-69cc-4f20-8cc0-0904a92b6a5e</id><userId>787f5ef4-410d-4185-b195-774a4f521da3</userId><iterations>0</iterations><enabled>true</enabled><status>APPROVED</status><roles><roles>administrator</roles></roles></user_login_password>**
thank you @ryansavino and @gwei3
