### ISSUE TITLE
libcrypto and libssl errors during installation

### ISSUE THREAD

**Issue by ge0rgi** [opencit/opencit#44]
I am having trouble installing OpenCIT on a fresh Ubuntu 14.04 
During the installation I get many errors saying "no version information available"

`libssl.so.1.0.0: no version information available (required by openssl)
/usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
/usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/psql)`

The installation goes one anyway until 

`Created user pcaadmin
Created user pcaadmin
Generating Data Encryption Key mtwilson.as.dek...
Configuring Mt Wilson Portal administrator username and password...
Username: [admin] admin
Password: [********] ********
Completed create-certificate-authority-key
Completed create-admin-user
` 

Afterwards I get some more fo the errors described above
`wget: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by wget)
`
 and the installation seems to hang forever. There is no CPU/Disk activity or anything indicating that something is happening.  
Is anyone having similar issues? This is a fresh install I have installed nothing but the software needed to build the project. I have not installed OpenSSL myself so it must have been installed during the installation. I also tried installing OpenSSL myself via the package manager, same result. Does OpenCIT require some special version of OpenSSL?

**Comment by ryansavino** [comment]
Are you behind a proxy?

**Comment by ge0rgi** [comment]
No proxy. I was able to download everything I needed for building using wget an maven without such errors or any special settings. When I use wget myself (not via the install binary) everything works fine as well, no errors or warnings. I am totally puzzled why it does work from the installation binary.

**Comment by ryansavino** [comment]
Can you tail /tmp/mtwilson-install.log file? Also, give the full console output. It will help me figure out what part of the install is hanging.

**Comment by ge0rgi** [comment]
Installer output:

`root@openstack-oat:~# ./mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit.bin 
Verifying archive integrity... All good.
Uncompressing mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit  100%  
Loading environment variables from /root/mtwilson.env
Installing Java...
Java already installed at /usr/lib/jvm/jdk1.7.0_51
Replacing java.security file, existing file will be backed up
/usr/lib/jvm/jdk1.7.0_51/jre/lib/security/java.security.2017-03-11.1200
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zip is already the newest version.
openssl is already the newest version.
unzip is already the newest version.
The following extra packages will be installed:
  libxslt1.1
The following NEW packages will be installed:
  authbind libxslt1.1 xmlstarlet
0 upgraded, 3 newly installed, 0 to remove and 3 not upgraded.
Need to get 455 kB of archives.
After this operation, 1,132 kB of additional disk space will be used.
Get:1 http://at.archive.ubuntu.com/ubuntu/ trusty/main libxslt1.1 amd64 1.1.28-2build1 [145 kB]
Get:2 http://at.archive.ubuntu.com/ubuntu/ trusty/universe xmlstarlet amd64 1.5.0-1 [290 kB]
Get:3 http://at.archive.ubuntu.com/ubuntu/ trusty/main authbind amd64 2.1.1 [19.6 kB]
Fetched 455 kB in 0s (772 kB/s)
Selecting previously unselected package libxslt1.1:amd64.
(Reading database ... 67061 files and directories currently installed.)
Preparing to unpack .../libxslt1.1_1.1.28-2build1_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.28-2build1) ...
Selecting previously unselected package xmlstarlet.
Preparing to unpack .../xmlstarlet_1.5.0-1_amd64.deb ...
Unpacking xmlstarlet (1.5.0-1) ...
Selecting previously unselected package authbind.
Preparing to unpack .../authbind_2.1.1_amd64.deb ...
Unpacking authbind (2.1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libxslt1.1:amd64 (1.1.28-2build1) ...
Setting up xmlstarlet (1.5.0-1) ...
Setting up authbind (2.1.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Extracting application...
Available TLS policies: certificate, certificate-digest, public-key, public-key-digest, TRUST_FIRST_CERTIFICATE, INSECURE
functions: line 462: digest,TRUST_FIRST_CERTIFICATE: command not found
Mt Wilson Allowed TLS Policies:  [] certificate,certificate-digest,public-key,public-key- digest,TRUST_FIRST_CERTIFICATE
Mt Wilson Default TLS Policy ID:  [TRUST_FIRST_CERTIFICATE] TRUST_FIRST_CERTIFICATE
Configuring Mt Wilson Server Name...
Please enter the IP Address or Hostname that will identify the Mt Wilson server.
This address will be used in the server SSL certificate and in all Mt Wilson URLs.
For example, if you enter '192.168.100.101' then the Mt Wilson URL is 
https://192.168.100.101:8181 (for Glassfish deployments) or 
https://192.168.100.101:8443 (for Tomcat deployments)
Detected the following options on this server:
+ 192.168.100.101
+ openstack-oat
Mt Wilson Server: [192.168.100.101] 10.219.35.146

Checking to see if postgresql package is available for install...
Configuring DB Connection...
Hostname: [127.0.0.1] 127.0.0.1
Port Num: [5432] 5432
Database: [mw_as] mw_as
Username: [root] root
Password: [********] ********
Installing postgres server...
Running postgresql auto install...
Extracting templates from packages: 100%
 * Setting up X socket directories...                                                             [ OK ] 
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
Adding user postgres to group ssl-cert

Creating config file /etc/logrotate.d/postgresql-common with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
 * No PostgreSQL clusters exist; see "man pg_createcluster"
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
/usr/lib/postgresql/9.3/bin/postgres: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/postgres)
Installing postgres client...
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/psql)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
Postgres client is already installed skipping...
Installation of postgres client complete
Creating database...
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/psql)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/psql)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
Replacing PostgreSQL local 'peer' authentication with 'password' authentication...
Installing Mt Wilson linux utility...
  100%  Mt Wilson linux utility installation done
Verifying archive integrity... All good.
Uncompressing tomcat-installer-7.0.34  100%  
Installing tomcat in /opt/mtwilson/share/apache-tomcat-7.0.34...
Adding manager roles to tomcat admin account in tomcat-users.xml...
Editing server.xml in /opt/mtwilson/share/apache-tomcat-7.0.34/conf...
Do you want to set up an SSL certificate for Tomcat? [Y/n] yes

Domain name[s] for SSL Certificate: [192.168.100.101,127.0.0.1] 10.219.35.146,127.0.0.1,192.168.1.59
Changing keystore password and updating in Tomcat server.xml...
Restarting Tomcat as a new Tomcat keystore password was set...
Creating SSL Certificate for 10.219.35.146,127.0.0.1,192.168.1.59...
Restarting Tomcat as a new SSL certificate was generated...
Certificate stored in file </opt/mtwilson/share/apache-tomcat-7.0.34/ssl/ssl.10.219.35.146.crt>
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
Installing mtwilson service...
Verifying archive integrity... All good.
Uncompressing mtwilson-attestation-service-installer-2.2-SNAPSHOT  100%  
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/psql)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/postgresql/9.3/bin/psql)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
/usr/lib/postgresql/9.3/bin/psql: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/libpq.so.5)
Database [mw_as] already exists
Scanning for postgresql SQL files
Certificate stored in file </etc/intel/cloudsecurity/saml.crt>
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
You need to set a username and password for administrators installing Trust Agents to access the Privacy CA service.
PrivacyCA Administrator Username: [admin] pcaadmin
PrivacyCA Administrator Password: [********] ********
Created user pcaadmin
Created user pcaadmin
Generating Data Encryption Key mtwilson.as.dek...
Configuring Mt Wilson Portal administrator username and password...
Username: [admin] admin
Password: [********] ********
Completed create-certificate-authority-key
Completed create-admin-user
wget: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by wget)
wget: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by wget)
wget: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by wget)
wget: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by wget)
Application is not deployed on Tomcat; skipping undeploy
wget: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by wget)
wget: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by wget)
`


Tail install log: 
`root@openstack-oat:~# tail /tmp/mtwilson-install.log 
postgres_pghb_conf=/etc/postgresql/9.3/main/pg_hba.conf
postgres_conf=/etc/postgresql/9.3/main/postgresql.conf
postgres_com=service postgresql
postgres_connect=/usr/bin/psql -h 127.0.0.1 -p 5432 -d mw_as -U root
asctl setup create-certificate-authority-key...
asctl setup create-admin-user...
webservice_application_name: mtwilson
TOMCAT_RUNNING: yes
webservice_application_name: mtwilson
TOMCAT_RUNNING: yes
`

I don't see anything wrong here so [here](https://gist.github.com/ge0rgi/603c371a884a2fbfa089cb1ee0696879) is the entire log.
`
`

**Comment by JiaJianZ** [comment]
Do you install mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit.bin in  source code compiler environment of opencit2.2
if you do  I suggest you install mtwilson-server-2.2-SNAPSHOT-jdk_glassfish_monit.bin in another machine
I've had the same problem and I separate them ,then it works

**Comment by ge0rgi** [comment]
Yes installing on different machine removes the errors
