### ISSUE TITLE
 Error from RequestEndorsementCertificate: Validation failed

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#5]
I get this error when I install the trust agent:

`5615 [main] ERROR c.i.m.s.console.cmd.SetupManager - Error from RequestEndorsementCertificate: Validation failed
5617 [main] WARN  c.i.m.s.console.cmd.SetupManager - Validating RequestEndorsementCertificate: Unable to verify TPM EC with 15 authorities from /opt/trustagent/configuration/endorsement.pem.EC is also not registered with Mt.Wilson
5619 [main] ERROR com.intel.dcsg.cpg.console.Main - Error while executing setup: Encountered errors during setup`

I tried again after installation:

> tagent setup

and:

> tagent authorize

but I get the same error.
I also tried in mtwilson:

> mtwilson setup SetupManager create-privacy-ca --no-exec
> mtwilson setup SetupManager create-endorsement-ca --no-exec

but apparently they dont work, I get:

> Unrecognized command

in /opt/mtwilson/configuration there are EndorsementCA.pem and EndorsementCA.p12 and
in /opt/tagent/configuration there is also a endorsement.pem

Could you guys help me with this problem ? I'm kind of lost

Greetings.

**Comment by ZahediAquino** [comment]
Can you please attach full catalina.out log from server? and the http.log and trustagent.log from the trust agent host (/opt/trustagent/logs/)?

**Comment by jemm14** [comment]
sure

[logs.zip](https://github.com/opencit/opencit/files/329351/logs.zip)
