### ISSUE TITLE
The resolution of "Detailed architecture" diagram of OpenCIT 3.2 is too low

### ISSUE THREAD

**Issue by boliurise** [opencit/opencit#52]
Can not see the flow notes on the diagram, please update clear one.

**Comment by lupitaost** [comment]
Hello,
We just updated the diagram.

**Comment by boliurise** [comment]
This one - https://github.com/opencit/opencit/blob/1622578454b6fc6c14189f3efade1074e4c7dfbc/documentation/product_guide/images/detailed%20architecture.jpg ?

**Comment by boliurise** [comment]
It's not updated

**Comment by ZahediAquino** [comment]
We updated it here:
https://github.com/opencit/opencit/wiki/Open-CIT-3.2-Product-Guide#20-intel-cloud-integrity-technology-architecture

**Comment by ZahediAquino** [comment]
You can right click on the image, open image in new tab and have a better view of it.
