### ISSUE TITLE
 opencit-util build error jacorb:jacorb:jar:2.2.3 dependancy not found.

### ISSUE THREAD

**Issue by ge0rgi** [opencit/opencit#53]
I am having trouble building `opencit-util` OpenCIT on Ubnut 16.04. During the build process of `com.intel.mtwilson.util:mtwilson-util-jpa:jar` the dependency  `jacorb:jacorb:jar:2.2.3-jonas-patch-20071018` is not found. This happens on both version 2.2 and 3.2. [Here](https://mvnrepository.com/artifact/org.jacorb/jacorb-idl/2.2.3-jonas-patch-20071018) I found out, that the library is not part of the maven central repository. I have added the Redhat GA repository to my settings.xml but I still get the following error when building:

` Failed to execute goal on project mtwilson-util-jpa: Could not resolve dependencies for project com.intel.mtwilson.util:mtwilson-util-jpa:jar:2.2-SNAPSHOT: Could not find artifact org.jacorb:jacorb:jar:2.2.3-jonas-patch-20071018 in rh-ga-repo (https://maven.repository.redhat.com/ga)`

Looking at the maven debug output I found the following
`Downloading: https://maven.repository.redhat.com/ga/org/jacorb/jacorb/2.2.3-jonas-patch-20071018/jacorb-2.2.3-jonas-patch-20071018.pom
[DEBUG] Writing tracking file /root/.m2/repository/org/jacorb/jacorb/2.2.3-jonas-patch-20071018/jacorb-2.2.3-jonas-patch-20071018.pom.lastUpdated
[WARNING] The POM for org.jacorb:jacorb:jar:2.2.3-jonas-patch-20071018 is missing, no dependency information available`

The file pointed by this URL really does not exist, the correct one would be https://maven.repository.redhat.com/ga/org/jacorb/jacorb-idl/2.2.3-jonas-patch-20071018/jacorb-idl-2.2.3-jonas-patch-20071018.jar

Is anyone having similar issues? how do I resolve this?

**Comment by ZahediAquino** [comment]
The repo where we built from during the release was ok, since then it seems to be on and off. We need to look into the issue a bit more, for now to get past your problem, you can update the following pom file:

util/mtwilson-util-jpa/pom.xml

Update the version in this section:

        <dependency>
            <groupId>org.ow2.jotm</groupId>
            <artifactId>jotm-core</artifactId>
            <version>2.2.3</version>
        </dependency>

from 2.2.3 to 2.3.1-M1. This should not be taken as a definite solution, but it will fix your problem for now. We will look into it.

**Comment by ge0rgi** [comment]
Ok works now. Should I close the issue or leave it open?
