### ISSUE TITLE
Barbican/KMIP prerequisite for CIT Key Management Service

### ISSUE THREAD

**Issue by mrcdb** [opencit/opencit#57]
The OpenCIT product guide states that OpenStack Barbican is a prerequisite for the installation of KMS, but according to this section [1], the KMS could use its internal valut in case a KMIP compliant key vault is not provided. Could you please clarify this point? Is Barbican/KMIP solution needed or just an optional requirement?

Thanks.

[1] https://github.com/opencit/opencit/wiki/Open-CIT-3.2-Product-Guide#10233-configuring-the-kms-to-use-an-external-barbican-or-kmip-compliant-key-vault

**Comment by ZahediAquino** [comment]
@mrcdb  thanks for pointing this out, we will update documentation accordingly, but the section with the correct information is: 4.3 Installing the Key Broker Service/4.3.1 Prerequisites.

For KMS you must either have KMIP or Barbicam configured.
