### ISSUE TITLE
I can't find cit-quickstart-linux-3.0  installer

### ISSUE THREAD

**Issue by blufon** [opencit/opencit#58]

**Comment by ZahediAquino** [comment]
After you build CIT, look under:
cit-quickstart-linux/target/

Is documentation pointing specifically to 3.0? the one you will find will either be 3.2 or 3.2.1 (depends on what you checked out).

**Comment by blufon** [comment]
Thanks for the quick reply.  What should i check out to build CIT. There are so many packages and got lost. just want to be able to create the Attestation server using the wizard

**Comment by ZahediAquino** [comment]
You should follow the instructions here to build:
https://github.com/opencit/opencit/wiki/Open-CIT-3.2.1-Product-Guide#142-intel-cit-source-code

Then look at this guide for the deployment:
https://github.com/opencit/opencit/blob/v3.2.1/documentation/product_guide/deployment%20wizard%20guide%203.2.pdf

**Comment by blufon** [comment]
Thanks, will follow that instructions and update my status.
Again thank you for the quick response.

**Comment by blufon** [comment]
Thank you so much. I was able to build all without any issue including the quickstart and i was able to see the Cloud Intergrity Technology portal

Verifying archive integrity... All good.
Uncompressing cit-quickstart-linux-3.2.1-SNAPSHOT  100%
Installing Cloud Integrity Technology (R)...
==================================================>100%

**Comment by ZahediAquino** [comment]
Great!
