### ISSUE TITLE
Endorsment Certificate from TPM not found in endorsment.pem from trust agent ??

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#6]
I get this error when I install the trust agent:

5615 [main] ERROR c.i.m.s.console.cmd.SetupManager - Error from RequestEndorsementCertificate: Validation failed 5617 [main] WARN c.i.m.s.console.cmd.SetupManager - Validating RequestEndorsementCertificate: Unable to verify TPM EC with 15 authorities from /opt/trustagent/configuration/endorsement.pem.EC is also not registered with Mt.Wilson 5619 [main] ERROR com.intel.dcsg.cpg.console.Main - Error while executing setup: Encountered errors during setup

I tried again after installation:

tagent setup
and:

tagent authorize
but I get the same error.
I also tried in mtwilson:

mtwilson setup SetupManager create-privacy-ca --no-exec
mtwilson setup SetupManager create-endorsement-ca --no-exec
but apparently they dont work, I get:

Unrecognized command
in /opt/mtwilson/configuration there are EndorsementCA.pem and EndorsementCA.p12 and
in /opt/tagent/configuration there is also a endorsement.pem

the logs (catalina.out, install.log, trustagent.log):

[logs.zip](https://github.com/opencit/opencit/files/330758/logs.zip)

Greetings.

**Comment by ZahediAquino** [comment]
Things to try:
1.  Check the date; you can check the cert start and expiry time with the keytool verbose command
a.  Ssl cert can be found in the tomcat keystore: /opt/mtwilson/share/apache…/ssl/.keystore
2.  Check the hosts file. From the keytool command output on the ssl cert, check the subject alternative names and check for the IPs and hostnames. Portal may connect with 127.0.0.1 or localhost, so make sure those entries are there as well
3.  You may have reinstalled. If you reinstalled and created a new ssl cert, but didn’t erase all the users beforehand, the system will reuse the users from the previous install and their keystore in the DB will have the old ssl cert, in which case I would recommend you delete the DB or try a clean install.

**Comment by jemm14** [comment]
@ZahediAquino ,

thank you, i solved it with point 3

**Comment by ZahediAquino** [comment]
Great.

**Comment by 19LukaModric** [comment]
@adolfovega Hi, I followed the 3 points of @ZahediAquino, but the error still exists. The related file and certification are listed as the follow.

keytool -printcert -file ssl.cert:
Owner: CN=10.0.5.5, CN=127.0.0.1, OU=Mt Wilson, O=Trusted Data Center, C=US
Issuer: CN=10.0.5.5, CN=127.0.0.1, OU=Mt Wilson, O=Trusted Data Center, C=US
Serial number: 27a73fcf
Valid from: Thu Oct 27 15:14:53 CST 2016 until: Sun Oct 25 15:14:53 CST 2026
Certificate fingerprints:
     MD5:  F9:82:0F:64:24:8E:F6:3E:2E:67:98:20:15:D7:7C:23
     SHA1: 8C:20:A9:32:56:CA:81:6D:63:AA:D8:B9:0A:F7:28:B2:3F:50:61:80
     SHA256: EB:0E:30:9E:A8:8F:B9:A6:85:9C:78:D8:55:B9:40:31:42:56:B1:AE:74:65:D6:00:51:DE:38:BB:9B:73:89:02
     Signature algorithm name: SHA256withRSA
     Version: 3

Extensions: 

#1: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  IPAddress: 10.0.5.5
  IPAddress: 127.0.0.1
]

#2: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C4 A8 C2 35 F0 9F 92 FE   C5 C9 79 72 FB 71 40 54  ...5......yr.q@T
0010: 5C EF 1F E0                                        ...
]
]

mtwilson.env:
export INSTALL_PKGS="java logrotate tomcat postgres privacyca monit SERVICES PORTALS"
export MTWILSON_SERVER=10.0.5.5
export MTWILSON_API_BASEURL="https://${MTWILSON_SERVER}:8443/mtwilson/v1"
export WEBSERVER_VENDOR=tomcat
export DATABASE_VENDOR=postgres
export DATABASE_PORTNUM=5432
export MC_FIRST_USERNAME=administrator
export MC_FIRST_PASSWORD=password
export TOMCAT_ADMIN_USERNAME=tomcatadmin
export TOMCAT_ADMIN_PASSWORD=setininstall
export PRIVACYCA_DOWNLOAD_USERNAME=pcaadmin
export PRIVACYCA_DOWNLOAD_PASSWORD=password
#####################################################################################################
export MTWILSON_TLS_POLICY_ALLOW=certificate,certificate-digest,public-key,public-key-digest,TRUST_FIRST_CERTIFICATE
export MTWILSON_DEFAULT_TLS_POLICY_ID=TRUST_FIRST_CERTIFICATE
#####################################################################################################
export LOG_ROTATION_PERIOD=daily
export LOG_COMPRESS=compress
export LOG_DELAYCOMPRESS=delaycompress
export LOG_COPYTRUNCATE=copytruncate
export LOG_SIZE=100M
export LOG_OLD=7
##################################################################################################### 
export JAVA_REQUIRED_VERSION=1.7.0_51
export MTWILSON_API_SSL_VERIFY_HOSTNAME=false
export DATABASE_HOSTNAME=127.0.0.1
export DATABASE_SCHEMA=mw_as
export DATABASE_USERNAME=root
export DATABASE_PASSWORD=password
#####################################################################################################
export POSTGRES_REQUIRED_VERSION=9.3
export POSTGRES_HOSTNAME=${DATABASE_HOSTNAME}
export POSTGRES_PORTNUM=${DATABASE_PORTNUM}
export POSTGRES_DATABASE=${DATABASE_SCHEMA}
export POSTGRES_USERNAME=${DATABASE_USERNAME}
export POSTGRES_PASSWORD=${DATABASE_PASSWORD}
export ADD_POSTGRESQL_REPO=yes
export POSTGRESQL_KEEP_PGPASS=true
##################################################################################################### 
export TOMCAT_REQUIRED_VERSION=7.0
export TOMCAT_CREATE_SSL_CERT=yes
export TOMCAT_SSL_CERT_CN=${MTWILSON_SERVER},127.0.0.1
export PRIVACYCA_SERVER=${MTWILSON_SERVER}
export INSTALLED_MARKER_FILE=/var/opt/intel/.mtwilsonInstalled
export INSTALL_LOG_FILE=/tmp/mtwilson-install.log
#####################################################################################################
export MTWILSON_TAG_SERVER_PRIVATE=${MTWILSON_SERVER}
export TAG_PROVISION_EXTERNAL=false
export TAG_PROVISION_NOCACHE=true
export TAG_PROVISION_XML_ENCRYPTION_REQUIRED=false
export TAG_PROVISION_XML_PASSWORD=password
export MTWILSON_TAG_KEYSTORE="/opt/mtwilson/configuration/serverAtag.jks"
export MTWILSON_TAG_KEYSTORE_PASSWORD=password
export MTWILSON_TAG_KEY_PASSWORD=password
export MTWILSON_TAG_CERT_IMPORT_AUTO=true
export TAG_PROVISION_XML_REQUIRED=false
export TAG_VALIDITY_SECONDS=31536000
export TAG_ISSUER_DN="CN=mtwilson-tag-ca"
export MTWILSON_TAG_HTML5_DIR="/opt/mtwilson/share/apache-tomcat-7.0.34/webapps/mtwilson-portal/tag"
export MTWILSON_TAG_ADMIN_USERNAME=tagadmin
export MTWILSON_TAG_ADMIN_PASSWORD=password

trustagent.env:
MTWILSON_API_URL=https://10.0.5.5:8443/mtwilson/v2
MTWILSON_API_USERNAME=pcaadmin
MTWILSON_API_PASSWORD=password
MTWILSON_TLS_CERT_SHA1=8c20a93256ca816d63aad8b90af728b23f506180
REGISTER_TPM_PASSWORD=y
TRUSTAGENT_LOGIN_REGISTER=true

**Comment by 19LukaModric** [comment]
Did the different version of the mtwilson api cased the error?

**Comment by 19LukaModric** [comment]
I have a question that how can I get MTWILSON_API_PASSWORD in trustagent.env? Is this argument the same as PRIVACYCA_DOWNLOAD_PASSWORD in mtwilson.env?
