### ISSUE TITLE
Unable to import white list ESXi hosts: IllegalArgumentException.  [MS_WHITELIST_CONFIG_ERROR] [3007]

### ISSUE THREAD

**Issue by yemaneb** [opencit/opencit#65]
Looking at the logs I see the below errors:

[http-bio-8443-exec-8] c.i.d.c.i.Message [Message.java:57] No translation for key MS_WHITELIST_CONFIG_ERROR in bund                                                                                                   le java.util.PropertyResourceBundle: Can't find resource for bundle java.util.PropertyResourceBundle, key MS_WHITELIST_CONFIG_ERROR
2017-08-15 16:56:15,566 ERROR [http-bio-8443-exec-8] c.i.d.c.i.Message [Message.java:58] Message MS_WHITELIST_CONFIG_ERROR args [IllegalArgumentE                                                                                                   xception]

**Comment by JordunoInt** [comment]
Do you know if you have the TPM enable on the ESXi host?

 If you are not sure how to verify if the TPM is enable or not, please follow the next guide: https://www.intel.com/content/dam/www/public/us/en/documents/guides/intel-one-stop-txt-activation-guide.pdf   section VMware ESXi 5.x page 11.

Also could you please let me know the version for ESXi that you have?

Regards

**Comment by yemaneb** [comment]
Thank you for your reply.  

Yes TPM is enabled and went through the guide you mentioned as well. Still getting the same error. I have ESXi-6.0.0


<img width="426" alt="esxi-tpm-info" src="https://user-images.githubusercontent.com/982121/29367990-7f310ef0-826c-11e7-8cdb-3eabc75362d4.PNG">

<img width="812" alt="vcenter-tpm-mob" src="https://user-images.githubusercontent.com/982121/29368129-d955d87a-826c-11e7-9e9e-acf3d81222bd.PNG">

**Comment by JordunoInt** [comment]
Could you please let me know, what are the steps that you are performing to do the whitelisting? and also, have you entered into the tust dashboard to check the trus report? it should display something like this: 
![image](https://user-images.githubusercontent.com/30439400/29369046-0fe6e79a-8267-11e7-8bc9-9e473c266f0c.png)

Could you please, enable debug mode to check the logs, please attach them, to take a look and see what could be happning. https://github.com/opencit/opencit/wiki/FAQ

**Comment by yemaneb** [comment]
Hello,

I have nothing to report as I don't have any host added yet as it needs MLE to be configured first. I am trying to do Whitelist using the "Import from Trusted host" then checking/enabling "register Host" to register it. .

This is the first time i am setting this up. I have VMware environment and from the guide i read i don't need to install/configure TrustAgent.    

What i have so far is that i build from source and created another VM and copied  the binary 
mtwilson-server-3.2.1-SNAPSHOT-jdk_glassfish_monit.bin  to the new VM and execute it. I modified mtwilson.env to match my environment and was completed sucessfully.

Then i went to the portal to do whitelist of an ESXi host and that's where i am stuck.  

Thanks for all your help.

**Comment by JordunoInt** [comment]
I was able to reproduce the issue, it can be two things so far.

I dont know if you are putting your correct credentials but it could be the reason, please take a look into the screenshot, and let me know if you are doing the same.

And also, it can be that your user doesnt have enough privileges for that.

![image](https://user-images.githubusercontent.com/30439400/29374068-c4d361fc-8275-11e7-9ea8-665d701018ed.png)

Please ignore the error at the bottom, it was from a previous test, but the screenshot shows what data you need.

Please let me know if it works or if you are doing something different.

**Comment by yemaneb** [comment]
Thanks,

will try that. I was logging in with my AD user which i though had enough priveleges.. as i was able to get to he mob and vCenter.   will try to use the administrator credentials.. and let you know.

Do you have an Archtectural diagram for opencit with vmware.. just want to make sure i have all the pieces.. 

Thanks

**Comment by yemaneb** [comment]
Hello yes.
i tried it with the administrator@vsphere.local  account and get the same error.
<img width="458" alt="esxi-whitelist-issue" src="https://user-images.githubusercontent.com/982121/29374550-cf110566-827f-11e7-9a48-b875319ac60d.PNG">

**Comment by JordunoInt** [comment]
the only diagram that we have right now, is the one listed on the product guide: https://github.com/opencit/opencit/wiki/Open-CIT-3.2.1-Product-Guide#20-intel-cloud-integrity-technology-architecture 

Keep me posted on the results that you get, you to know if t works or not

**Comment by yemaneb** [comment]
yes i am stuck.

I just want to make sure what else that i am missing.  LIke i mention the only thing i have up and running is the "mtwilson-portal".   Am my missing any other installation i need to do like Trust Director, etc.. to be able to whitelist esxi hosts.

Thanks.

**Comment by JordunoInt** [comment]
I notice that you are trying to use a "host certificate" in the TLS Policy, and in my example, i use "trust first certificate" could please try using that? no, i dont think you are missing something.... another thing is when you select on the TLS host certifcate...are your providing the HEX or Base64-encoded DER-format X.509 public key certificate? i try with the host certificate without providing the cert and it fails, but it is expected, because it needs the cert, so please let me know

**Comment by yemaneb** [comment]
Thanks,

I don't see that option on the pull down menu.. i only see (Host certficate, Host certificate fingerprint and Host public key'

<img width="266" alt="tls-policy" src="https://user-images.githubusercontent.com/982121/29376040-2b8b3e7e-8285-11e7-80b9-188e1bfa912c.PNG">

**Comment by JordunoInt** [comment]
Could you please provide me your env file, because it seems that something it is wrong, you should be able to see many different options.

**Comment by yemaneb** [comment]
export INSTALL_PKGS="java logrotate tomcat postgres privacyca monit SERVICES PORTALS"
export MTWILSON_SERVER=<Removed the IP>
export MTWILSON_API_BASEURL="https://${MTWILSON_SERVER}:8443/mtwilson/v1"
export WEBSERVER_VENDOR=tomcat
export DATABASE_VENDOR=postgres
export DATABASE_PORTNUM=5432
export MC_FIRST_USERNAME=administrator
export MC_FIRST_PASSWORD=password
export TOMCAT_ADMIN_USERNAME=tomcatadmin
export TOMCAT_ADMIN_PASSWORD=setininstall
export PRIVACYCA_DOWNLOAD_USERNAME=pcaadmin
export PRIVACYCA_DOWNLOAD_PASSWORD=password
#####################################################################################################
export MTWILSON_TLS_POLICY_ALLOW=certificate,certificate-digest,public-key,public-key- digest,TRUST_FIRST_CERTIFICATE
export MTWILSON_DEFAULT_TLS_POLICY_ID=TRUST_FIRST_CERTIFICATE
#####################################################################################################
export LOG_ROTATION_PERIOD=daily export LOG_COMPRESS=compress
export LOG_DELAYCOMPRESS=delaycompress export LOG_COPYTRUNCATE=copytruncate
export LOG_SIZE=100M
export LOG_OLD=7
#####################################################################################################
export JAVA_REQUIRED_VERSION=1.7.0_51
export MTWILSON_API_SSL_VERIFY_HOSTNAME=false
export DATABASE_HOSTNAME=127.0.0.1
export DATABASE_SCHEMA=mw_as
export DATABASE_USERNAME=root
export DATABASE_PASSWORD=password
#####################################################################################################
export POSTGRES_REQUIRED_VERSION=9.3
export POSTGRES_HOSTNAME=${DATABASE_HOSTNAME}
export POSTGRES_PORTNUM=${DATABASE_PORTNUM}
export POSTGRES_DATABASE=${DATABASE_SCHEMA}
export POSTGRES_USERNAME=${DATABASE_USERNAME}
export POSTGRES_PASSWORD=${DATABASE_PASSWORD}
export ADD_POSTGRESQL_REPO=yes
export POSTGRESQL_KEEP_PGPASS=true
#####################################################################################################
export TOMCAT_REQUIRED_VERSION=7.0
export TOMCAT_CREATE_SSL_CERT=yes
export TOMCAT_SSL_CERT_CN=${MTWILSON_SERVER},127.0.0.1
export PRIVACYCA_SERVER=${MTWILSON_SERVER}
export INSTALLED_MARKER_FILE=/var/opt/intel/.mtwilsonInstalled
export INSTALL_LOG_FILE=/tmp/mtwilson-install.log
#####################################################################################################
# ASSET TAG Configuration
export MTWILSON_TAG_SERVER_PRIVATE=${MTWILSON_SERVER}
export TAG_PROVISION_EXTERNAL=false
export TAG_PROVISION_NOCACHE=true
export TAG_PROVISION_XML_ENCRYPTION_REQUIRED=false
export TAG_PROVISION_XML_PASSWORD=password
export MTWILSON_TAG_KEYSTORE="/opt/mtwilson/configuration/serverAtag.jks"
export MTWILSON_TAG_KEYSTORE_PASSWORD=password
export MTWILSON_TAG_KEY_PASSWORD=password
export MTWILSON_TAG_CERT_IMPORT_AUTO=true
export TAG_PROVISION_XML_REQUIRED=false
export TAG_VALIDITY_SECONDS=31536000
export TAG_ISSUER_DN="CN=mtwilson-tag-ca"
export MTWILSON_TAG_HTML5_DIR="/opt/mtwilson/share/apache-tomcat-7.0.34/webapps/mtwilson-portal/tag"
export MTWILSON_TAG_ADMIN_USERNAME=tagadmin
export MTWILSON_TAG_ADMIN_PASSWORD=password

**Comment by yemaneb** [comment]
could this be a problem.  i noticed there is a space in "public-key- digest" on the mtwilson.env file.
export MTWILSON_TLS_POLICY_ALLOW=certificate,certificate-digest,public-key,public-key- digest,TRUST_FIRST_CERTIFICATE

i copied from the guide. And the guide had the space.

Thanks

**Comment by yemaneb** [comment]
i am reinstalling now.. corrected the space.. i did "mtwilson uninstall" and installing now.  will let you know..

Thanks

**Comment by JordunoInt** [comment]
I have a few more things in mind that could be causing the issue, but if it works reinstalling and deleting the spaces, that would be great

**Comment by yemaneb** [comment]
Now it does not show me any TLS Policy to chose from.  And it will not let me create TLS shared policy from Adminstration section either.  So i tried just to see and i get  "java.security.cert.CertificateException: Server certificate is not trusted"

i will do it again. 
mtwilson stop
mtwilson erase-users --all
mtwilson erase-data --all
mtwilson uninstall

Thanks, will let you know

**Comment by yemaneb** [comment]
Thank you so much for all your help. 

After fixing the space and reuning the installation all look good. I was able to import the ESXi host with TRUST_FIRST_Certficate 

<img width="304" alt="tls-policy-good" src="https://user-images.githubusercontent.com/982121/29378202-38640aca-828c-11e7-9246-4c944e0c8c06.PNG">

<img width="291" alt="success" src="https://user-images.githubusercontent.com/982121/29378212-3c116c08-828c-11e7-8cd7-494c5c5e3475.PNG">

<img width="616" alt="whitelisted-1" src="https://user-images.githubusercontent.com/982121/29378216-3e6d78a2-828c-11e7-98af-5d763e68e55c.PNG">

**Comment by JordunoInt** [comment]
No problem, anytime :)
