### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by jeefberkey** [opencit/opencit#68]
Is there a place I can download a compiled and signed package or installer for my platform? (CentOS 7)

**Comment by JordunoInt** [comment]
Hello Jeff,

Answering your question...there is not a compiled or signed package that we cant distribute, you need to follow  the instructions here: https://github.com/opencit/opencit/wiki/Open-CIT-3.2.1-Product-Guide#140-building-opencit-from-source.

I hope it helps you.

Regards,
Jorge O.
