### ISSUE TITLE
Problem using IBM software TPM

### ISSUE THREAD

**Issue by jemm14** [opencit/opencit#9]
I am using the IBM software TPM (http://ibmswtpm.sourceforge.net/) to proof the attestation of the openCIT in a educational project for my university (thm.de).
When I install the trust agent in the host I get the following error:

`6891 [main] ERROR c.i.m.s.console.cmd.SetupManager - Error from RequestEndorsementCertificate: Validation failed
6891 [main] WARN  c.i.m.s.console.cmd.SetupManager - Validating RequestEndorsementCertificate: Unable to verify TPM EC with 15 authorities from /opt/trustagent/configuration/endorsement.pem.EC is also not registered with Mt.Wilson`

so apparently the Endorsement certificate from the IBM software TPM is not inlcuded in the list of recognized authorities of endorsement.pem.
Without the validation of the EC, the AIK certificate cannot be verified either and I cannot add any host through Import White List from Trusted Host. (catalina.out):

`2016-06-28 09:36:34,031 ERROR [http-bio-8443-exec-5] c.i.m.m.b.HostBO [HostBO.java:935] Cannot encode AIK certificate: java.lang.NullPointerException
java.lang.NullPointerException: null`

is there any way to succed in this validation using only the public endorsement key or EC of the IBM software TPM or any way to avoid this validation to add the host and proof the attestation, considering that this is a educational project (no production enviroment) and the machine I use (Acer Aspire E5 ) unfortunately doesnt have the TPM chip.

Please help me with this. This is, I think, the last step I have to solve to proof the attestation

Greetings.

**Comment by ZahediAquino** [comment]
It won't work on simulators. You need a physical host with a physical TPM Chip. TXT Technology  and TPM Chip are part of the building blocks required.
